title: Ishaan Chandak
description: Blogs written by Ishaan Chandak

url: https://long-haul.netlify.app
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about
    - title: Contact
      url: /contact

social:
    github: Ishaan-Chandak
    twitter: brianmaierjr
    facebook: brianmaierjr
    email: ishaanchandak3@gmail.com
    linkedin: ishaan-chandak-558b0822b

google_analytics: "UA-58263416-1"

disqus:
    shortname: brianmaierjr
